### ISSUE TITLE
What is this? Please extend README

### ISSUE THREAD

**Issue by paulvi** [mdexSwap/apyrobot#2]
It is not clear what exactly this repo for.

I guess it is for APY calculation, yet I have found do docs for APY or MDX reward calculation

**Comment by dsky1990** [comment]
This is a local service that we used to display apy data in the early days.

**Comment by mdexSwap** [comment]
This is a local service that we used to display apy data in the early days.

**Comment by paulvi** [comment]
apy.json is still being undated

Where do APY come from now?

**Comment by mdexSwap** [comment]
@paulvi boardroom or liquidity? you can get it from our server

**Comment by paulvi** [comment]
Because APY/APR is not within subgraph data for LP, I was looking for way to get it automatically.
https://mdex.com/#/liquidity APY data is different from https://apy.mdex.com/ that seems to be calculated by apyrobot. 

Website https://mdex.com/#/liquidity shows APRs, but if there is way to get it automatically via API call ?
