### ISSUE TITLE
How to get APR values shown on https://mdex.com/#/liquidity 

### ISSUE THREAD

**Issue by paulvi** [mdexSwap/apyrobot#3]
continued from #2 

Because APY/APR is not within subgraph data for LP, I was looking for way to get it automatically.
https://mdex.com/#/liquidity APY data is different from https://apy.mdex.com/ that seems to be calculated by apyrobot.

Website https://mdex.com/#/liquidity shows APRs, but if there is way to get it automatically via API call ?

**Comment by mdexSwap** [comment]
you can use this api `https://gateway.mdex.cc/v2/mingpool/lps?mdex_chainid=chainid`
